In [1]:
import pandas as pd

In [4]:
structure_energies = pd.read_csv('structure_energies.csv',header=5)
structure_energies

,Model,fGln123,Val51,Structure,Geom opt (Hartee),Relative Geom opt (kcal/mol),Single pt (Hartree),Relative Single pt (kcal/mol),Single pt (Hartree) BS3,Relative Single pt (kcal/mol) BS3,Relative Difference (BS3-BS2)
0,Inactive,Inactive,Inactive,ES,-5709.9320,0.00,-5713.9090,0.00,-5712.5237,0.00,0.00
1,Inactive,Inactive,Inactive,TS1,-5709.9280,3.01,-5713.9040,3.17,-5712.5179,3.67,0.49
2,Inactive,Inactive,Inactive,INT1,-5709.9390,-3.91,-5713.9130,-2.87,-5712.5279,-2.65,0.23
3,Inactive,Inactive,Inactive,TS2,-5709.8950,23.27,-5713.8720,23.24,-5712.4812,26.69,3.45
4,Inactive,Inactive,Inactive,INT2,-5709.8970,22.43,-5713.8680,25.37,-5712.4809,26.88,1.51
5,Inactive,Inactive,Inactive,TS3,-5709.8880,28.01,-5713.8600,30.52,-5712.4718,32.58,2.05
6,Inactive,Inactive,Inactive,INT3,-5709.8970,22.02,-5713.8700,24.60,-5712.4820,26.16,1.57
7,Inactive,Inactive,Inactive,TS4,-5709.8860,28.88,-5713.8660,26.61,-5712.4755,30.27,3.65
8,Inactive,Inactive,Inactive,INT4,-5709.8930,24.80,-5713.8750,21.29,-5712.4869,23.12,1.83
9,Active,Active,Active,ES,-5709.9730,0.00,-5713.9380,0.00,-5712.5540,0.00,0.00
10,Active,Active,Active,TS1,-5709.9470,16.09,-5713.9150,14.53,-5712.5282,16.19,1.66
11,Active,Active,Active,INT1,-5709.9710,0.96,-5713.9370,0.88,-5712.5495,2.83,1.95
12,Active,Active,Active,TS2,-5709.9480,15.88,-5713.9150,14.49,-5712.5246,18.45,3.95
13,Active,Active,Active,INT2,-5709.9620,6.81,-5713.9200,11.43,-5712.5334,12.90,1.47
14,Active,Active,Active,TS3,-5709.9510,13.62,-5713.9110,16.71,-5712.5240,18.82,2.11
15,Active,Active,Active,INT3,-5709.9540,12.05,-5713.9160,13.76,-5712.5289,15.72,1.95
16,Active,Active,Active,TS4,-5709.9410,19.71,-5713.9080,18.68,-5712.5171,23.15,4.47
17,Active,Active,Active,INT4,-5709.9630,5.99,-5713.9300,4.82,-5712.5427,7.06,2.24
18,Inactive fGln123,Inactive,Active,ES,-5709.9220,0.00,-5713.9000,0.00,NaN,NaN,NaN
19,Inactive fGln123,Inactive,Active,TS2,-5709.9000,14.11,-5713.8790,12.56,NaN,NaN,NaN
20,Inactive fGln123,Inactive,Active,TS3,-5709.8980,15.24,-5713.8710,17.65,NaN,NaN,NaN
21,Inactive fGln123,Inactive,Active,TS4,-5709.8900,20.11,-5713.8710,17.77,NaN,NaN,NaN
22,Inactive Val51,Active,Inactive,ES,-5709.9609,0.00,-5713.9296,0.00,NaN,NaN,NaN
23,Inactive Val51,Active,Inactive,TS2,-5709.9439,10.62,-5713.9139,9.82,NaN,NaN,NaN
24,Inactive Val51,Active,Inactive,TS3,-5709.9393,13.51,-5713.9033,16.47,NaN,NaN,NaN
25,Inactive Val51,Active,Inactive,TS4,-5709.9216,24.63,-5713.9026,16.89,NaN,NaN,NaN

In [3]:
nbo_data = pd.read_csv('nbo_data.csv',header=3)
nbo_data

,Model,fGln123,Val51,Structure,Residue,Orbital,Interaction with LP 1,Interaction with LP 2,Interaction with LP 3,Total contribution
0,Active,Active,Active,TS1,Val51,BD*( 1) N 22- C 23,4.25,10.49,NaN,14.74
1,Active,Active,Active,TS1,Gly52,BD*( 1) N 29- H224,3.80,0.24,NaN,4.04
2,Active,Active,Active,TS1,Leu85,BD*( 1) N 39- H154,2.63,0.00,NaN,2.63
3,Active,Active,Active,TS2,Val51,BD*( 1) N 98- H232,7.19,11.31,4.31,22.81
4,Active,Active,Active,TS2,Gly52,BD*( 1) N105- H228,3.43,1.49,3.13,8.05
5,Active,Active,Active,TS2,Leu85,BD*( 1) N 5- H 53,7.71,0.00,8.70,16.41
6,Active,Active,Active,TS3,Val51,BD*( 1) N202- H236,0.00,0.00,NaN,0.00
7,Active,Active,Active,TS3,Gly52,BD*( 1) N203- H232,3.88,5.84,NaN,9.72
8,Active,Active,Active,TS3,Leu85,BD*( 1) N 44- H 68,5.09,4.21,NaN,9.30
9,Inactive fGln123,Inactive,Active,TS1,Val51,BD*( 1) N118- H152,4.79,10.64,NaN,15.43
10,Inactive fGln123,Inactive,Active,TS1,Gly52,BD*( 1) N119- H148,2.74,0.30,NaN,3.04
11,Inactive fGln123,Inactive,Active,TS1,Leu85,BD*( 1) N190- H205,2.51,0.00,NaN,2.51
12,Inactive fGln123,Inactive,Active,TS2,Val51,BD*( 1) N161- H195,7.02,11.62,4.83,23.47
13,Inactive fGln123,Inactive,Active,TS2,Gly52,BD*( 1) N162- H191,3.56,1.46,3.15,8.17
14,Inactive fGln123,Inactive,Active,TS2,Leu85,BD*( 1) N 5- H 29,7.09,0.00,7.96,15.05
15,Inactive fGln123,Inactive,Active,TS3,Val51,BD*( 1) N166- H200,0.06,0.05,NaN,0.11
16,Inactive fGln123,Inactive,Active,TS3,Gly52,BD*( 1) N167- H196,3.70,5.44,NaN,9.14
17,Inactive fGln123,Inactive,Active,TS3,Leu85,BD*( 1) N 8- H 32,4.89,4.17,NaN,9.06
18,Inactive Val51 (active Gly52),Active,Inactive,TS1,Gly50,BD*( 2) C232- O233,0.10,0.07,NaN,0.17
19,Inactive Val51 (active Gly52),Active,Inactive,TS1,Val51,BD*( 1) C 44- H 64,0.00,0.00,NaN,0.00
20,Inactive Val51 (active Gly52),Active,Inactive,TS1,Gly52,BD*( 1) N 41- H 65,9.16,1.66,NaN,10.82
21,Inactive Val51 (active Gly52),Active,Inactive,TS1,Leu85,BD*( 1) N 69- H 84,4.49,0.48,NaN,4.97
22,Inactive Val51 (active Gly52),Active,Inactive,TS2,Gly50,BD*( 2) C232- O233,0.23,0.11,NaN,0.34
23,Inactive Val51 (active Gly52),Active,Inactive,TS2,Val51,BD*( 1) C212- H140,0.00,0.00,0.00,0.00
24,Inactive Val51 (active Gly52),Active,Inactive,TS2,Gly52,BD*( 1) N117- H141,7.31,4.97,9.82,22.10
25,Inactive Val51 (active Gly52),Active,Inactive,TS2,Leu85,BD*( 1) N 5- H 30,7.20,2.34,9.63,19.17
26,Inactive Val51 (active Gly52),Active,Inactive,TS3,Gly50,BD*( 2) C232- O233,0.15,0.09,0.00,0.24
27,Inactive Val51 (active Gly52),Active,Inactive,TS3,Val51,BD*( 1) C205- H225,0.00,0.00,0.00,0.00
28,Inactive Val51 (active Gly52),Active,Inactive,TS3,Gly52,BD*( 1) N202- H226,7.71,3.36,11.09,22.16
29,Inactive Val51 (active Gly52),Active,Inactive,TS3,Leu85,BD*( 1) N 44- H 68,6.76,0.00,8.37,15.13
30,Inactive Val51 (inactive Gly52),Active,Inactive,TS1,Gly50,BD*( 2) C206- O215,0.43,0.28,0.06,0.77
31,Inactive Val51 (inactive Gly52),Active,Inactive,TS1,Val51,BD*( 1) C207- H225,0.00,0.00,0.00,0.00
32,Inactive Val51 (inactive Gly52),Active,Inactive,TS1,Gly52,BD*( 1) N203- H233,0.00,0.00,0.00,0.00
33,Inactive Val51 (inactive Gly52),Active,Inactive,TS1,Leu85,BD*( 1) N 43- H 67,6.07,0.00,8.22,14.29
34,Inactive Val51 (inactive Gly52),Active,Inactive,TS2,Gly50,BD*( 2) C207- O216,0.47,0.11,0.06,0.64
35,Inactive Val51 (inactive Gly52),Active,Inactive,TS2,Val51,BD*( 1) C208- H226,0.00,0.00,0.00,0.00
36,Inactive Val51 (inactive Gly52),Active,Inactive,TS2,Gly52,BD*( 1) N204- H234,0.00,0.00,0.00,0.00
37,Inactive Val51 (inactive Gly52),Active,Inactive,TS2,Leu85,BD*( 1) N 44- H 68,7.44,1.69,10.96,20.09
38,Inactive Val51 (inactive Gly52),Active,Inactive,TS3,Gly50,BD*( 2) C207- O216,0.34,0.00,NaN,0.34
39,Inactive Val51 (inactive Gly52),Active,Inactive,TS3,Val51,BD*( 1) C208- H226,0.00,0.00,NaN,0.00
40,Inactive Val51 (inactive Gly52),Active,Inactive,TS3,Gly52,BD*( 1) N204- H234,0.00,0.00,NaN,0.00
41,Inactive Val51 (inactive Gly52),Active,Inactive,TS3,Leu85,BD*( 1) N 44- H 68,4.58,4.57,NaN,9.15
42,Inactive,Inactive,Inactive,TS1,Val51,BD*( 1) C 23- H167,5.86,0.15,NaN,6.01
43,Inactive,Inactive,Inactive,TS1,Gly52,BD*( 1) N 29- H175,0.08,0.34,NaN,0.42
44,Inactive,Inactive,Inactive,TS1,Leu85,BD*( 1) N 39- H156,3.72,0.53,NaN,4.25
45,Inactive,Inactive,Inactive,TS2,Val51,BD*( 1) C 23- H167,5.49,0.24,0.92,6.65
46,Inactive,Inactive,Inactive,TS2,Gly52,BD*( 1) N 29- H175,0.00,0.21,0.33,0.54
47,Inactive,Inactive,Inactive,TS2,Leu85,BD*( 1) N 39- H156,2.88,0.81,4.11,7.80
48,Inactive,Inactive,Inactive,TS3,Val51,BD*( 1) C 23- H167,4.92,0.74,NaN,5.66
49,Inactive,Inactive,Inactive,TS3,Gly52,BD*( 1) N 29- H175,0.00,0.43,NaN,0.43
50,Inactive,Inactive,Inactive,TS3,Leu85,BD*( 1) N 39- H156,0.00,0.00,NaN,0.00

In [5]:
# Note this data does not yet contain the Inactive Val51 (active Gly52) results because those calculations are still running.
almo_eda_data = pd.read_csv('almo-eda_data.csv',header=4)
almo_eda_data

,Model,fGln123,Val51,Structure,∆ELEC (kcal/mol),∆SOLV (kcal/mol),∆PAULI (kcal/mol),∆DISP (kcal/mol),∆POL (kcal/mol),∆CT (kcal/mol),∆TOTAL INT E (kcal/mol)
0,Inactive,Inactive,Inactive,ES,-35.39,12.85,23.19,-8.56,-1.67,-3.47,-13.05
1,Inactive,Inactive,Inactive,TS1,-31.00,11.30,20.70,-8.00,-1.20,-3.00,-11.20
2,Inactive,Inactive,Inactive,TS2,-30.30,10.80,20.50,-7.90,-1.20,-3.00,-11.10
3,Inactive,Inactive,Inactive,TS3,-31.90,11.30,21.50,-7.50,-1.50,-3.20,-11.40
4,Active,Active,Active,ES,-88.37,16.34,92.68,-31.94,-4.78,-13.08,-29.15
5,Active,Active,Active,TS1,-86.60,15.10,91.40,-31.60,-4.50,-12.80,-29.00
6,Active,Active,Active,TS2,-86.30,15.30,90.60,-31.40,-4.40,-12.60,-28.80
7,Active,Active,Active,TS3,-87.20,15.30,92.10,-32.20,-4.50,-12.70,-29.10
8,Inactive fGln123,Inactive,Active,ES,-11.11,5.64,5.91,-4.89,-0.16,-0.73,-5.35
9,Inactive fGln123,Inactive,Active,TS1,-9.90,5.10,4.90,-4.60,-0.10,-0.70,-5.30
10,Inactive fGln123,Inactive,Active,TS2,-9.50,4.50,5.60,-4.70,-0.10,-0.70,-5.00
11,Inactive fGln123,Inactive,Active,TS3,-9.30,4.30,5.70,-4.90,-0.20,-0.70,-5.10
12,Inactive Val51,Active,Inactive,ES,-89.54,15.17,94.75,-33.94,-4.36,-12.73,-30.64
13,Inactive Val51,Active,Inactive,TS1,-73.00,14.90,77.10,-31.70,-3.00,-9.60,-25.30
14,Inactive Val51,Active,Inactive,TS2,-72.10,14.70,75.80,-31.80,-2.90,-9.60,-25.80
15,Inactive Val51,Active,Inactive,TS3,-76.40,14.50,81.00,-33.50,-3.00,-10.10,-27.50